spring:
  datasource:
    url: jdbc:mysql://localhost:3306/todolist_app_db
    username: root
    password: bestuser
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  jooq:
    sql-dialect: org.hibernate.dialect.MySQL8Dialect
  cassandra:
    port: 8080
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    operations-sorter: method
server:
  error:
    include-message: always
jwt_access_secret: SSBoYXZlIG5vIGVuZW1pZXMK
jwt_refresh_secret: VGhlcmUgaXMgbm8gb25lIGluIHRoaXMgd29ybGQgeW91IG5lZWQgdG8gaHVydAo=